# Generated by Django 2.1.1 on 2018-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmarks_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks_data',
            name='path',
            field=models.CharField(default='#', max_length=256),
        ),
    ]
